### PR TITLE
Ali splash before dash (welcome page)

### LINKED ISSUE #75: Create splash before dashboard
There are no designs for it but I was thinking we just display a few stats (use existing routes) and then have a button to the main dashboard

Please talk with Cindy

EDIT: The design is now in the Figma.

### PR DESCRIPTION
**Pull request by a3alani**
## Tracking Info

Resolves #75

## Changes

1. I modified the welcome.html to match the Figma design
2. I added CSS styling in welcome.css to match the Figma design
3. I added a event listener in welcome.js to populate the fields (tasks to-do, tasks completed, streak, num of snippets) by fetching the data and processing it

## Testing

- I tested it by running the server.js and fetching the data from the database
- Used live server too for the front end testing

## Confirmation of Change

Screenshot 2024-06-09 at 7 37 15 PM

### CODE REVIEW

**Review by dylantrann — CHANGES_REQUESTED** [review]
The styling looks great! There are two functionality issues though, as it seems like the snippet and streak counts aren't displaying properly. 

---

## Snippets
Here there are three snippets in the database, but the welcome page still only displays 1 (even after reload). The snippets count seems to be stuck at 1, even with more and more snippets being added (as it stuck to one when there were 0, 1, 2, and 3 snippets total).

image
image

## Streaks
According to both the dashboard and database, the streak shouldn't be 11 but it displays it as so. The 11 that is being displayed is likely the total SiteVisits registered in the database (as seen being 11 in the phot below) but it should be only 1. 
image
image
image

--- 

Once these issue are fixed, it should be good to ship!

**Comment by a3alani** [comment]
Good catch! I had an mistake in processing the data. Should be fixed now:

Screenshot 2024-06-09 at 8 43 34 PM

**Comment by a3alani** [comment]
Here it updated the snippets as I added a new one:

Screenshot 2024-06-09 at 8 49 01 PM

For the streak, I added some logic to calculate it based on the dates returned from the streak query.

**Review by dylantrann — APPROVED** [review]
Looks good, great job!

Tested with Docker and local server.

**Pull request merged**
